UPDATE `ploopi_mod_doc_file_draft` SET `md5id` = '' WHERE ISNULL(`md5id`);
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `md5id` `md5id` char(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_draft` SET `id_docfile` = 0  WHERE ISNULL(`id_docfile`);
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `id_docfile` `id_docfile` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_draft` SET `name` = '' WHERE ISNULL(`name`);
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `name` `name` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_draft` SET `description` = '' WHERE ISNULL(`description`);
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `description` `description` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_draft` SET `timestp_create` = 0  WHERE ISNULL(`timestp_create`);
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `timestp_create` `timestp_create` bigint(14) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_draft` SET `size` = 0  WHERE ISNULL(`size`);
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `size` `size` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_draft` SET `extension` = '' WHERE ISNULL(`extension`);
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `extension` `extension` varchar(20) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_draft` SET `parents` = '' WHERE ISNULL(`parents`);
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `parents` `parents` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_draft` SET `id_folder` = 0  WHERE ISNULL(`id_folder`);
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `id_folder` `id_folder` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_meta` SET `meta` = '' WHERE ISNULL(`meta`);
ALTER TABLE `ploopi_mod_doc_meta` CHANGE `meta` `meta` varchar(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_meta` SET `value` = '' WHERE ISNULL(`value`);
ALTER TABLE `ploopi_mod_doc_meta` CHANGE `value` `value` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_parser` SET `extension` = '' WHERE ISNULL(`extension`);
ALTER TABLE `ploopi_mod_doc_parser` CHANGE `extension` `extension` varchar(10) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_history` SET `id_docfile` = 0  WHERE ISNULL(`id_docfile`);
ALTER TABLE `ploopi_mod_doc_file_history` CHANGE `id_docfile` `id_docfile` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_history` SET `name` = '' WHERE ISNULL(`name`);
ALTER TABLE `ploopi_mod_doc_file_history` CHANGE `name` `name` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_history` SET `description` = '' WHERE ISNULL(`description`);
ALTER TABLE `ploopi_mod_doc_file_history` CHANGE `description` `description` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_history` SET `timestp_create` = 0  WHERE ISNULL(`timestp_create`);
ALTER TABLE `ploopi_mod_doc_file_history` CHANGE `timestp_create` `timestp_create` bigint(14) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_history` SET `timestp_modify` = 0  WHERE ISNULL(`timestp_modify`);
ALTER TABLE `ploopi_mod_doc_file_history` CHANGE `timestp_modify` `timestp_modify` bigint(14) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_history` SET `size` = 0  WHERE ISNULL(`size`);
ALTER TABLE `ploopi_mod_doc_file_history` CHANGE `size` `size` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file_history` SET `extension` = '' WHERE ISNULL(`extension`);
ALTER TABLE `ploopi_mod_doc_file_history` CHANGE `extension` `extension` varchar(20) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `md5id` = '' WHERE ISNULL(`md5id`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `md5id` `md5id` char(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `name` = '' WHERE ISNULL(`name`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `name` `name` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `description` = '' WHERE ISNULL(`description`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `description` `description` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `timestp_create` = 0  WHERE ISNULL(`timestp_create`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `timestp_create` `timestp_create` bigint(14) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `timestp_modify` = 0  WHERE ISNULL(`timestp_modify`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `timestp_modify` `timestp_modify` bigint(14) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `size` = 0  WHERE ISNULL(`size`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `size` `size` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `extension` = '' WHERE ISNULL(`extension`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `extension` `extension` varchar(20) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `parents` = '' WHERE ISNULL(`parents`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `parents` `parents` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `content` = '' WHERE ISNULL(`content`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `content` `content` longtext NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `nbclick` = 0  WHERE ISNULL(`nbclick`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `nbclick` `nbclick` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `metadata` = '' WHERE ISNULL(`metadata`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `metadata` `metadata` longtext NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `words_overall` = 0  WHERE ISNULL(`words_overall`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `words_overall` `words_overall` int(10) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `words_indexed` = 0  WHERE ISNULL(`words_indexed`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `words_indexed` `words_indexed` int(10) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `id_folder` = 0  WHERE ISNULL(`id_folder`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `id_folder` `id_folder` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `id_user_modify` = 0  WHERE ISNULL(`id_user_modify`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `id_user_modify` `id_user_modify` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `id_user` = 0  WHERE ISNULL(`id_user`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `id_user` `id_user` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `id_workspace` = 0  WHERE ISNULL(`id_workspace`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `id_workspace` `id_workspace` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_file` SET `id_module` = 0  WHERE ISNULL(`id_module`);
ALTER TABLE `ploopi_mod_doc_file` CHANGE `id_module` `id_module` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_keyword` SET `keyword` = '' WHERE ISNULL(`keyword`);
ALTER TABLE `ploopi_mod_doc_keyword` CHANGE `keyword` `keyword` varchar(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_keyword` SET `twoletters` = '' WHERE ISNULL(`twoletters`);
ALTER TABLE `ploopi_mod_doc_keyword` CHANGE `twoletters` `twoletters` char(2) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_folder` SET `name` = '' WHERE ISNULL(`name`);
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `name` `name` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_folder` SET `description` = '' WHERE ISNULL(`description`);
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `description` `description` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_folder` SET `parents` = '' WHERE ISNULL(`parents`);
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `parents` `parents` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mod_doc_folder` SET `timestp_create` = 0  WHERE ISNULL(`timestp_create`);
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `timestp_create` `timestp_create` bigint(14) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_folder` SET `timestp_modify` = 0  WHERE ISNULL(`timestp_modify`);
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `timestp_modify` `timestp_modify` bigint(14) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_folder` SET `id_folder` = 0  WHERE ISNULL(`id_folder`);
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `id_folder` `id_folder` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_folder` SET `id_user_modify` = 0  WHERE ISNULL(`id_user_modify`);
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `id_user_modify` `id_user_modify` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_folder` SET `id_user` = 0  WHERE ISNULL(`id_user`);
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `id_user` `id_user` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_folder` SET `id_workspace` = 0  WHERE ISNULL(`id_workspace`);
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `id_workspace` `id_workspace` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mod_doc_folder` SET `id_module` = 0  WHERE ISNULL(`id_module`);
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `id_module` `id_module` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
