DROP TABLE IF EXISTS `ploopi_mod_nanogallery`;

CREATE TABLE IF NOT EXISTS `ploopi_mod_nanogallery` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` tinyint(10) UNSIGNED NOT NULL DEFAULT '0',
  `id_workspace` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `id_module` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `label` varchar(255) NOT NULL DEFAULT '',
  `description` varchar(256) NOT NULL DEFAULT '',
  `id_folder` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `frameBgColor` varchar(20) NOT NULL DEFAULT '',
  `frameBorderColor` varchar(20) NOT NULL DEFAULT '',
  `frameBorderVertical` int(10) NOT NULL DEFAULT '0',
  `frameBorderHorizontal` int(10) NOT NULL DEFAULT '0',
  `frameBorderRadius` int(10) NOT NULL DEFAULT '0',
  `frameInternalVertical` int(11) NOT NULL DEFAULT '0',
  `frameInternalHorizontal` int(11) NOT NULL DEFAULT '0',
  `frameExternalVertical` int(11) NOT NULL DEFAULT '0',
  `frameExternalHorizontal` int(11) NOT NULL DEFAULT '0',
  `galleryLayout` varchar(32) NOT NULL DEFAULT 'grid',
  `thumbnailOpenImage` tinyint(1) NOT NULL DEFAULT '1',
  `thumbnailWidth` varchar(10) NOT NULL DEFAULT '200',
  `thumbnailHeight` varchar(10) NOT NULL DEFAULT '200',
  `thumbnailBorderVertical` int(4) UNSIGNED NOT NULL DEFAULT '2',
  `thumbnailBorderHorizontal` int(4) UNSIGNED NOT NULL DEFAULT '2',
  `thumbnailBorderColor` varchar(32) NOT NULL DEFAULT '#000000',
  `thumbnailBgColor` varchar(32) NOT NULL DEFAULT '#444444',
  `galleryDisplayMode` varchar(32) NOT NULL DEFAULT 'fullContent',
  `galleryMaxRows` int(4) UNSIGNED NOT NULL DEFAULT '2',
  `galleryDisplayMoreStep` int(4) UNSIGNED NOT NULL DEFAULT '2',
  `galleryLastRowFull` tinyint(1) NOT NULL DEFAULT '0',
  `galleryPaginationMode` varchar(32) NOT NULL DEFAULT 'rectangles',
  `thumbnailDisplayTransition` varchar(32) NOT NULL DEFAULT 'fadeIn',
  `thumbnailDisplayTransitionDuration` int(10) UNSIGNED NOT NULL DEFAULT '240',
  `thumbnailDisplayInterval` int(10) UNSIGNED NOT NULL DEFAULT '15',
  `thumbnailLabelDisplay` tinyint(1) NOT NULL DEFAULT '1',
  `thumbnailLabelPosition` varchar(32) NOT NULL DEFAULT 'overImageOnBottom',
  `thumbnailLabelAlignement` varchar(32) NOT NULL DEFAULT 'center',
  `thumbnailLabelTitleMultiline` tinyint(1) NOT NULL DEFAULT '0',
  `thumbnailLabelDisplayDescription` tinyint(1) NOT NULL DEFAULT '0',
  `thumbnailLabelDescriptionMultiline` tinyint(1) NOT NULL DEFAULT '0',
  `thumbnailAlignment` varchar(32) NOT NULL DEFAULT 'center',
  `gallerySorting` varchar(32) NOT NULL DEFAULT '',
  `galleryMaxItems` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `thumbnailGutterWidth` int(4) UNSIGNED NOT NULL DEFAULT '2',
  `thumbnailGutterHeight` int(4) UNSIGNED NOT NULL DEFAULT '2',
  `thumbnailHoverEffect1` varchar(32) NOT NULL DEFAULT 'toolsAppear',
  `thumbnailHoverEffect2` varchar(32) NOT NULL DEFAULT 'scale120',
  `thumbnailHoverEffect3` varchar(32) NOT NULL DEFAULT '',
  `displayBreadcrumb` tinyint(1) NOT NULL DEFAULT '1',
  `breadcrumbAutoHideTopLevel` tinyint(1) NOT NULL DEFAULT '1',
  `breadcrumbOnlyCurrentLevel` tinyint(1) NOT NULL DEFAULT '1',
  `galleryFilterTags` varchar(32) NOT NULL DEFAULT 'false',
  `thumbnailLevelUp` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

