#!/usr/bin/php
<?php
/*
    Copyright (c) 2007-2009 Ovensia
    Contributors hold Copyright (c) to their code submissions.

    This file is part of Ploopi.

    Ploopi is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Ploopi is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Ploopi; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

/**
 * Point d'entrée pour la ligne de commande
 * Permet d'exécuter des opérations de maintenance
 *
 * @package ploopi
 * @subpackage cli
 * @copyright Ovensia
 * @license GNU General Public License (GPL)
 * @author Stéphane Escaich
 *
 */

/**
 * On se positionne dans le dossier de l'application
 * pour éviter les problèmes d'include.
 * Solution temporaire en attendant mieux.
 */

chdir(dirname(__FILE__));

/**
 * Chargement de l'environnement
 */

define('_PLOOPI_DIRNAME',  dirname(__FILE__));

include_once './include/classes/loader.php';

ploopi\loader::boot_cli();


$booHelp = false;

// Traitement des arguments
for ($i=1;$i<$argc;$i++)
{
    if($argv[$i] == '--help')
    {
        $booHelp = true;
        break;
    }

    $arrArg = preg_split('/=/', $argv[$i]);
    if (sizeof($arrArg) == 2) // argument valide
    {
        ${$arrArg[0]} = $arrArg[1];
    }
}

if($booHelp)
{
    echo<<<STDOUT
Usage: {$argv[0]} module=[MODULE]... action=[ACTION]...\r
Effectuer une action automatique propre au module ploopi\r
Réindexation, génération de vignettes,...\r\n
  module=MODULE     indique le module responsable de l'action à effectuer\r
                    (ex. doc)\r
  action=ACTION     l'action à effectuer\r
                    (ex. reindex, thumbnails)\n
STDOUT;
}
elseif (!empty($module) && !empty($action))
{
    $strControllerFile = "ploopi\\{$module}\\controller";
    if (ploopi\loader::classExists($strControllerFile)) {
        // Wrapper pour compatibilité avec le contrôleur du module
        $_REQUEST['entity'] = 'cli';
        $_REQUEST['action'] = $action;
        $strControllerFile::dispatch();
    }
    else {
        // Rétrocompatibilité
        if (file_exists("./modules/{$module}/cli.php"))
        {
            include_once "./modules/{$module}/cli.php";
        }
        else
        {
            echo "module '{$module}' inconnu\n";
        }
    }
}
else
{
    echo<<<STDOUT
cli : paramètre manquant\r
Pour en savoir davantage, faites: « ./cli --help ».\n
STDOUT;
}
