#!/usr/bin/php
<?php
/*
    Copyright (c) 2007-2009 Ovensia
    Contributors hold Copyright (c) to their code submissions.

    This file is part of Ploopi.

    Ploopi is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Ploopi is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Ploopi; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

/**
 * Point d'entrée les appels via CRON
 *
 * @package ploopi
 * @subpackage cron
 * @copyright Ovensia
 * @license GNU General Public License (GPL)
 * @author Stéphane Escaich
 *
 * <code>
 * * * * * * /var/www/ploopi/cron > /dev/null 2>&1
 * </code>
 */

/**
 * On se positionne dans le dossier de l'application
 * pour éviter les problèmes d'include.
 * Solution temporaire en attendant mieux.
 */

chdir(dirname(__FILE__));

/**
 * Chargement de l'environnement
 */

define('_PLOOPI_DIRNAME',  dirname(__FILE__));

include_once './include/classes/loader.php';

ploopi\loader::boot_cli();

$db = ploopi\loader::getdb();

$cron_rs = $db->query("
    SELECT      label
    FROM        ploopi_module_type
");

while ($cron_fields = $db->fetchrow($cron_rs))
{
    $strControllerFile = "ploopi\\{$cron_fields['label']}\\controller";
    if (ploopi\loader::classExists($strControllerFile)) {
        // Wrapper pour compatibilité avec le contrôleur du module
        $_REQUEST['entity'] = 'cron';
        $strControllerFile::dispatch();
    }
    else {
        // Rétrocompatibilité
        $cronfile = "./modules/{$cron_fields['label']}/cron.php";
        if (file_exists($cronfile)) include $cronfile;
    }
}

ploopi_die();
?>
