DROP TABLE IF EXISTS `ploopi_mod_forms_graphic`;
CREATE TABLE IF NOT EXISTS `ploopi_mod_forms_graphic` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `id_form` int(10) unsigned NOT NULL default '0',
  `label` varchar(255) NOT NULL,
  `description` longtext NOT NULL,
  `type` enum('pie','pie3d','bar','barc','line','linec') NOT NULL,
  `percent` tinyint(1) unsigned NOT NULL default '0',
  `filled` tinyint(1) unsigned NOT NULL default '0',
  `line_aggregation` enum('hour','day','week','month') NOT NULL,
  `operation` enum('count','sum','avg') NOT NULL,
  `line1_field` int(10) unsigned NOT NULL default '0',
  `line2_field` int(10) unsigned NOT NULL default '0',
  `line3_field` int(10) unsigned NOT NULL default '0',
  `line4_field` int(10) unsigned NOT NULL default '0',
  `line5_field` int(10) unsigned NOT NULL default '0',
  `line1_operation` varchar(16) NOT NULL,
  `line2_operation` varchar(16) NOT NULL,
  `line3_operation` varchar(16) NOT NULL,
  `line4_operation` varchar(16) NOT NULL,
  `line5_operation` varchar(16) NOT NULL,
  `line1_color` varchar(16) NOT NULL,
  `line2_color` varchar(16) NOT NULL,
  `line3_color` varchar(16) NOT NULL,
  `line4_color` varchar(16) NOT NULL,
  `line5_color` varchar(16) NOT NULL,
  `line1_filter_op` varchar(16) NOT NULL,
  `line2_filter_op` varchar(16) NOT NULL,
  `line3_filter_op` varchar(16) NOT NULL,
  `line4_filter_op` varchar(16) NOT NULL,
  `line5_filter_op` varchar(16) NOT NULL,
  `line1_filter_value` varchar(255) NOT NULL,
  `line2_filter_value` varchar(255) NOT NULL,
  `line3_filter_value` varchar(255) NOT NULL,
  `line4_filter_value` varchar(255) NOT NULL,
  `line5_filter_value` varchar(255) NOT NULL,
  `pie_field` int(10) unsigned NOT NULL default '0',
  `pie_color1` varchar(16) NOT NULL,
  `pie_color2` varchar(16) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
