UPDATE `ploopi_log` SET `request_method` = '' WHERE ISNULL(`request_method`);
ALTER TABLE `ploopi_log` CHANGE `request_method` `request_method` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_log` SET `query_string` = '' WHERE ISNULL(`query_string`);
ALTER TABLE `ploopi_log` CHANGE `query_string` `query_string` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_log` SET `remote_addr` = '' WHERE ISNULL(`remote_addr`);
ALTER TABLE `ploopi_log` CHANGE `remote_addr` `remote_addr` varchar(64) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_log` SET `remote_port` = 0  WHERE ISNULL(`remote_port`);
ALTER TABLE `ploopi_log` CHANGE `remote_port` `remote_port` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_log` SET `script_filename` = '' WHERE ISNULL(`script_filename`);
ALTER TABLE `ploopi_log` CHANGE `script_filename` `script_filename` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_log` SET `path_translated` = '' WHERE ISNULL(`path_translated`);
ALTER TABLE `ploopi_log` CHANGE `path_translated` `path_translated` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_log` SET `script_name` = '' WHERE ISNULL(`script_name`);
ALTER TABLE `ploopi_log` CHANGE `script_name` `script_name` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_log` SET `request_uri` = '' WHERE ISNULL(`request_uri`);
ALTER TABLE `ploopi_log` CHANGE `request_uri` `request_uri` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_log` SET `browser` = '' WHERE ISNULL(`browser`);
ALTER TABLE `ploopi_log` CHANGE `browser` `browser` varchar(64) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_log` SET `system` = '' WHERE ISNULL(`system`);
ALTER TABLE `ploopi_log` CHANGE `system` `system` varchar(64) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_log` SET `total_exec_time` = 0  WHERE ISNULL(`total_exec_time`);
ALTER TABLE `ploopi_log` CHANGE `total_exec_time` `total_exec_time` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_log` SET `sql_exec_time` = 0  WHERE ISNULL(`sql_exec_time`);
ALTER TABLE `ploopi_log` CHANGE `sql_exec_time` `sql_exec_time` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_log` SET `sql_percent_time` = 0  WHERE ISNULL(`sql_percent_time`);
ALTER TABLE `ploopi_log` CHANGE `sql_percent_time` `sql_percent_time` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_log` SET `php_percent_time` = 0  WHERE ISNULL(`php_percent_time`);
ALTER TABLE `ploopi_log` CHANGE `php_percent_time` `php_percent_time` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_log` SET `numqueries` = 0  WHERE ISNULL(`numqueries`);
ALTER TABLE `ploopi_log` CHANGE `numqueries` `numqueries` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_log` SET `page_size` = 0  WHERE ISNULL(`page_size`);
ALTER TABLE `ploopi_log` CHANGE `page_size` `page_size` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_tag` SET `tag` = '' WHERE ISNULL(`tag`);
ALTER TABLE `ploopi_tag` CHANGE `tag` `tag` char(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_tag` SET `tag_clean` = '' WHERE ISNULL(`tag_clean`);
ALTER TABLE `ploopi_tag` CHANGE `tag_clean` `tag_clean` char(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_validation` SET `id_record` = '' WHERE ISNULL(`id_record`);
ALTER TABLE `ploopi_validation` CHANGE `id_record` `id_record` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_validation` SET `type_validation` = '' WHERE ISNULL(`type_validation`);
ALTER TABLE `ploopi_validation` CHANGE `type_validation` `type_validation` varchar(16) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_validation` SET `id_validation` = 0  WHERE ISNULL(`id_validation`);
ALTER TABLE `ploopi_validation` CHANGE `id_validation` `id_validation` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_validation` SET `id_module_type` = 0  WHERE ISNULL(`id_module_type`);
ALTER TABLE `ploopi_validation` CHANGE `id_module_type` `id_module_type` int(10) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_module` SET `id_workspace` = 0  WHERE ISNULL(`id_workspace`);
ALTER TABLE `ploopi_module` CHANGE `id_workspace` `id_workspace` int(10) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_module` SET `public` = 0  WHERE ISNULL(`public`);
ALTER TABLE `ploopi_module` CHANGE `public` `public` tinyint(1) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_module` SET `shared` = 0  WHERE ISNULL(`shared`);
ALTER TABLE `ploopi_module` CHANGE `shared` `shared` tinyint(1) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_module` SET `herited` = 0  WHERE ISNULL(`herited`);
ALTER TABLE `ploopi_module` CHANGE `herited` `herited` tinyint(1) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_module` SET `adminrestricted` = 0  WHERE ISNULL(`adminrestricted`);
ALTER TABLE `ploopi_module` CHANGE `adminrestricted` `adminrestricted` tinyint(1) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_module` SET `viewmode` = 0  WHERE ISNULL(`viewmode`);
ALTER TABLE `ploopi_module` CHANGE `viewmode` `viewmode` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_module` SET `transverseview` = 0  WHERE ISNULL(`transverseview`);
ALTER TABLE `ploopi_module` CHANGE `transverseview` `transverseview` tinyint(1) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_module` SET `autoconnect` = 0  WHERE ISNULL(`autoconnect`);
ALTER TABLE `ploopi_module` CHANGE `autoconnect` `autoconnect` tinyint(1) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_index_keyword_element` SET `id_element` = 0  WHERE ISNULL(`id_element`);
ALTER TABLE `ploopi_index_keyword_element` CHANGE `id_element` `id_element` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_index_keyword_element` SET `keyword` = '' WHERE ISNULL(`keyword`);
ALTER TABLE `ploopi_index_keyword_element` CHANGE `keyword` `keyword` char(20) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_annotation` SET `content` = '' WHERE ISNULL(`content`);
ALTER TABLE `ploopi_annotation` CHANGE `content` `content` longtext NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_annotation` SET `type_annotation` = '' WHERE ISNULL(`type_annotation`);
ALTER TABLE `ploopi_annotation` CHANGE `type_annotation` `type_annotation` varchar(16) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_annotation` SET `date_annotation` = '' WHERE ISNULL(`date_annotation`);
ALTER TABLE `ploopi_annotation` CHANGE `date_annotation` `date_annotation` varchar(14) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_annotation` SET `id_record` = '' WHERE ISNULL(`id_record`);
ALTER TABLE `ploopi_annotation` CHANGE `id_record` `id_record` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_annotation` SET `id_object` = 0  WHERE ISNULL(`id_object`);
ALTER TABLE `ploopi_annotation` CHANGE `id_object` `id_object` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_annotation` SET `id_user` = 0  WHERE ISNULL(`id_user`);
ALTER TABLE `ploopi_annotation` CHANGE `id_user` `id_user` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_annotation` SET `id_workspace` = 0  WHERE ISNULL(`id_workspace`);
ALTER TABLE `ploopi_annotation` CHANGE `id_workspace` `id_workspace` int(10) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_annotation` SET `id_module` = 0  WHERE ISNULL(`id_module`);
ALTER TABLE `ploopi_annotation` CHANGE `id_module` `id_module` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_annotation` SET `id_module_type` = 0  WHERE ISNULL(`id_module_type`);
ALTER TABLE `ploopi_annotation` CHANGE `id_module_type` `id_module_type` int(10) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_user_action_log` SET `id_record` = '' WHERE ISNULL(`id_record`);
ALTER TABLE `ploopi_user_action_log` CHANGE `id_record` `id_record` char(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user_action_log` SET `ip` = '' WHERE ISNULL(`ip`);
ALTER TABLE `ploopi_user_action_log` CHANGE `ip` `ip` char(16) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user_action_log` SET `user` = '' WHERE ISNULL(`user`);
ALTER TABLE `ploopi_user_action_log` CHANGE `user` `user` char(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user_action_log` SET `workspace` = '' WHERE ISNULL(`workspace`);
ALTER TABLE `ploopi_user_action_log` CHANGE `workspace` `workspace` char(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user_action_log` SET `action` = '' WHERE ISNULL(`action`);
ALTER TABLE `ploopi_user_action_log` CHANGE `action` `action` char(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user_action_log` SET `module_type` = '' WHERE ISNULL(`module_type`);
ALTER TABLE `ploopi_user_action_log` CHANGE `module_type` `module_type` char(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user_action_log` SET `module` = '' WHERE ISNULL(`module`);
ALTER TABLE `ploopi_user_action_log` CHANGE `module` `module` char(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_param_workspace` SET `value` = '' WHERE ISNULL(`value`);
ALTER TABLE `ploopi_param_workspace` CHANGE `value` `value` text NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_index_phonetic_element` SET `id_element` = 0  WHERE ISNULL(`id_element`);
ALTER TABLE `ploopi_index_phonetic_element` CHANGE `id_element` `id_element` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_index_phonetic_element` SET `phonetic` = '' WHERE ISNULL(`phonetic`);
ALTER TABLE `ploopi_index_phonetic_element` CHANGE `phonetic` `phonetic` char(20) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_session` SET `id` = '' WHERE ISNULL(`id`);
ALTER TABLE `ploopi_session` CHANGE `id` `id` char(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_session` SET `access` = 0  WHERE ISNULL(`access`);
ALTER TABLE `ploopi_session` CHANGE `access` `access` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_session` SET `data` = '' WHERE ISNULL(`data`);
ALTER TABLE `ploopi_session` CHANGE `data` `data` longblob NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_param_choice` SET `displayed_value` = '' WHERE ISNULL(`displayed_value`);
ALTER TABLE `ploopi_param_choice` CHANGE `displayed_value` `displayed_value` varchar(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_workspace` SET `id_workspace` = 0  WHERE ISNULL(`id_workspace`);
ALTER TABLE `ploopi_workspace` CHANGE `id_workspace` `id_workspace` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_workspace` SET `code` = '' WHERE ISNULL(`code`);
ALTER TABLE `ploopi_workspace` CHANGE `code` `code` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_workspace` SET `parents` = '' WHERE ISNULL(`parents`);
ALTER TABLE `ploopi_workspace` CHANGE `parents` `parents` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_workspace` SET `iprules` = '' WHERE ISNULL(`iprules`);
ALTER TABLE `ploopi_workspace` CHANGE `iprules` `iprules` text NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_workspace` SET `macrules` = '' WHERE ISNULL(`macrules`);
ALTER TABLE `ploopi_workspace` CHANGE `macrules` `macrules` text NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_workspace` SET `template` = '' WHERE ISNULL(`template`);
ALTER TABLE `ploopi_workspace` CHANGE `template` `template` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_workspace` SET `mustdefinerule` = 0  WHERE ISNULL(`mustdefinerule`);
ALTER TABLE `ploopi_workspace` CHANGE `mustdefinerule` `mustdefinerule` tinyint(1) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_workspace` SET `backoffice` = 0  WHERE ISNULL(`backoffice`);
ALTER TABLE `ploopi_workspace` CHANGE `backoffice` `backoffice` tinyint(1) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_workspace` SET `frontoffice` = 0  WHERE ISNULL(`frontoffice`);
ALTER TABLE `ploopi_workspace` CHANGE `frontoffice` `frontoffice` tinyint(1) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_workspace` SET `backoffice_domainlist` = '' WHERE ISNULL(`backoffice_domainlist`);
ALTER TABLE `ploopi_workspace` CHANGE `backoffice_domainlist` `backoffice_domainlist` longtext NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_workspace` SET `meta_description` = '' WHERE ISNULL(`meta_description`);
ALTER TABLE `ploopi_workspace` CHANGE `meta_description` `meta_description` longtext NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_workspace` SET `meta_keywords` = '' WHERE ISNULL(`meta_keywords`);
ALTER TABLE `ploopi_workspace` CHANGE `meta_keywords` `meta_keywords` longtext NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_workspace` SET `frontoffice_domainlist` = '' WHERE ISNULL(`frontoffice_domainlist`);
ALTER TABLE `ploopi_workspace` CHANGE `frontoffice_domainlist` `frontoffice_domainlist` longtext NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_param_default` SET `value` = '' WHERE ISNULL(`value`);
ALTER TABLE `ploopi_param_default` CHANGE `value` `value` text NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_index_stem_element` SET `id_element` = 0  WHERE ISNULL(`id_element`);
ALTER TABLE `ploopi_index_stem_element` CHANGE `id_element` `id_element` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_index_stem_element` SET `stem` = '' WHERE ISNULL(`stem`);
ALTER TABLE `ploopi_index_stem_element` CHANGE `stem` `stem` char(20) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_connecteduser` SET `ip` = '' WHERE ISNULL(`ip`);
ALTER TABLE `ploopi_connecteduser` CHANGE `ip` `ip` char(15) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_connecteduser` SET `domain` = '' WHERE ISNULL(`domain`);
ALTER TABLE `ploopi_connecteduser` CHANGE `domain` `domain` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_connecteduser` SET `user_id` = 0  WHERE ISNULL(`user_id`);
ALTER TABLE `ploopi_connecteduser` CHANGE `user_id` `user_id` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_connecteduser` SET `workspace_id` = 0  WHERE ISNULL(`workspace_id`);
ALTER TABLE `ploopi_connecteduser` CHANGE `workspace_id` `workspace_id` int(10) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_connecteduser` SET `module_id` = 0  WHERE ISNULL(`module_id`);
ALTER TABLE `ploopi_connecteduser` CHANGE `module_id` `module_id` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_connecteduser` SET `timestp` = 0  WHERE ISNULL(`timestp`);
ALTER TABLE `ploopi_connecteduser` CHANGE `timestp` `timestp` bigint(14) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mb_field` SET `label` = '' WHERE ISNULL(`label`);
ALTER TABLE `ploopi_mb_field` CHANGE `label` `label` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_field` SET `type` = '' WHERE ISNULL(`type`);
ALTER TABLE `ploopi_mb_field` CHANGE `type` `type` varchar(50) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_field` SET `visible` = 0  WHERE ISNULL(`visible`);
ALTER TABLE `ploopi_mb_field` CHANGE `visible` `visible` tinyint(1) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_param_user` SET `value` = '' WHERE ISNULL(`value`);
ALTER TABLE `ploopi_param_user` CHANGE `value` `value` text NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_folder` SET `md5id` = '' WHERE ISNULL(`md5id`);
ALTER TABLE `ploopi_documents_folder` CHANGE `md5id` `md5id` varchar(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_folder` SET `name` = '' WHERE ISNULL(`name`);
ALTER TABLE `ploopi_documents_folder` CHANGE `name` `name` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_folder` SET `description` = '' WHERE ISNULL(`description`);
ALTER TABLE `ploopi_documents_folder` CHANGE `description` `description` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_folder` SET `parents` = '' WHERE ISNULL(`parents`);
ALTER TABLE `ploopi_documents_folder` CHANGE `parents` `parents` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_folder` SET `timestp_create` = 0  WHERE ISNULL(`timestp_create`);
ALTER TABLE `ploopi_documents_folder` CHANGE `timestp_create` `timestp_create` bigint(14) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_folder` SET `timestp_modify` = 0  WHERE ISNULL(`timestp_modify`);
ALTER TABLE `ploopi_documents_folder` CHANGE `timestp_modify` `timestp_modify` bigint(14) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_folder` SET `id_folder` = 0  WHERE ISNULL(`id_folder`);
ALTER TABLE `ploopi_documents_folder` CHANGE `id_folder` `id_folder` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_folder` SET `id_user_modify` = 0  WHERE ISNULL(`id_user_modify`);
ALTER TABLE `ploopi_documents_folder` CHANGE `id_user_modify` `id_user_modify` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_folder` SET `id_user` = 0  WHERE ISNULL(`id_user`);
ALTER TABLE `ploopi_documents_folder` CHANGE `id_user` `id_user` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_folder` SET `id_workspace` = 0  WHERE ISNULL(`id_workspace`);
ALTER TABLE `ploopi_documents_folder` CHANGE `id_workspace` `id_workspace` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_folder` SET `id_module` = 0  WHERE ISNULL(`id_module`);
ALTER TABLE `ploopi_documents_folder` CHANGE `id_module` `id_module` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_folder` SET `id_record` = '' WHERE ISNULL(`id_record`);
ALTER TABLE `ploopi_documents_folder` CHANGE `id_record` `id_record` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `lastname` = '' WHERE ISNULL(`lastname`);
ALTER TABLE `ploopi_user` CHANGE `lastname` `lastname` varchar(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `firstname` = '' WHERE ISNULL(`firstname`);
ALTER TABLE `ploopi_user` CHANGE `firstname` `firstname` varchar(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `login` = '' WHERE ISNULL(`login`);
ALTER TABLE `ploopi_user` CHANGE `login` `login` varchar(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `password` = '' WHERE ISNULL(`password`);
ALTER TABLE `ploopi_user` CHANGE `password` `password` varchar(128) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `email` = '' WHERE ISNULL(`email`);
ALTER TABLE `ploopi_user` CHANGE `email` `email` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `phone` = '' WHERE ISNULL(`phone`);
ALTER TABLE `ploopi_user` CHANGE `phone` `phone` varchar(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `fax` = '' WHERE ISNULL(`fax`);
ALTER TABLE `ploopi_user` CHANGE `fax` `fax` varchar(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `comments` = '' WHERE ISNULL(`comments`);
ALTER TABLE `ploopi_user` CHANGE `comments` `comments` text NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `address` = '' WHERE ISNULL(`address`);
ALTER TABLE `ploopi_user` CHANGE `address` `address` text NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `mobile` = '' WHERE ISNULL(`mobile`);
ALTER TABLE `ploopi_user` CHANGE `mobile` `mobile` varchar(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `entity` = '' WHERE ISNULL(`entity`);
ALTER TABLE `ploopi_user` CHANGE `entity` `entity` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `service` = '' WHERE ISNULL(`service`);
ALTER TABLE `ploopi_user` CHANGE `service` `service` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `service2` = '' WHERE ISNULL(`service2`);
ALTER TABLE `ploopi_user` CHANGE `service2` `service2` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `function` = '' WHERE ISNULL(`function`);
ALTER TABLE `ploopi_user` CHANGE `function` `function` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `number` = '' WHERE ISNULL(`number`);
ALTER TABLE `ploopi_user` CHANGE `number` `number` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `postalcode` = '' WHERE ISNULL(`postalcode`);
ALTER TABLE `ploopi_user` CHANGE `postalcode` `postalcode` varchar(16) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `city` = '' WHERE ISNULL(`city`);
ALTER TABLE `ploopi_user` CHANGE `city` `city` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `country` = '' WHERE ISNULL(`country`);
ALTER TABLE `ploopi_user` CHANGE `country` `country` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `timezone` = '' WHERE ISNULL(`timezone`);
ALTER TABLE `ploopi_user` CHANGE `timezone` `timezone` varchar(64) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `building` = '' WHERE ISNULL(`building`);
ALTER TABLE `ploopi_user` CHANGE `building` `building` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `floor` = '' WHERE ISNULL(`floor`);
ALTER TABLE `ploopi_user` CHANGE `floor` `floor` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `office` = '' WHERE ISNULL(`office`);
ALTER TABLE `ploopi_user` CHANGE `office` `office` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `civility` = '' WHERE ISNULL(`civility`);
ALTER TABLE `ploopi_user` CHANGE `civility` `civility` varchar(16) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_user` SET `rank` = '' WHERE ISNULL(`rank`);
ALTER TABLE `ploopi_user` CHANGE `rank` `rank` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_wce_object` SET `id` = 0  WHERE ISNULL(`id`);
ALTER TABLE `ploopi_mb_wce_object` CHANGE `id` `id` int(11) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mb_wce_object` SET `label` = '' WHERE ISNULL(`label`);
ALTER TABLE `ploopi_mb_wce_object` CHANGE `label` `label` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_wce_object` SET `script` = '' WHERE ISNULL(`script`);
ALTER TABLE `ploopi_mb_wce_object` CHANGE `script` `script` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_wce_object` SET `select_id` = '' WHERE ISNULL(`select_id`);
ALTER TABLE `ploopi_mb_wce_object` CHANGE `select_id` `select_id` varchar(64) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_wce_object` SET `select_label` = '' WHERE ISNULL(`select_label`);
ALTER TABLE `ploopi_mb_wce_object` CHANGE `select_label` `select_label` varchar(64) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_wce_object` SET `select_table` = '' WHERE ISNULL(`select_table`);
ALTER TABLE `ploopi_mb_wce_object` CHANGE `select_table` `select_table` varchar(64) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_table` SET `label` = '' WHERE ISNULL(`label`);
ALTER TABLE `ploopi_mb_table` CHANGE `label` `label` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_table` SET `visible` = 0  WHERE ISNULL(`visible`);
ALTER TABLE `ploopi_mb_table` CHANGE `visible` `visible` tinyint(1) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_subscription_action` SET `id_subscription` = '' WHERE ISNULL(`id_subscription`);
ALTER TABLE `ploopi_subscription_action` CHANGE `id_subscription` `id_subscription` char(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_ext` SET `filetype` = '' WHERE ISNULL(`filetype`);
ALTER TABLE `ploopi_documents_ext` CHANGE `filetype` `filetype` varchar(16) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_subscription` SET `id` = '' WHERE ISNULL(`id`);
ALTER TABLE `ploopi_subscription` CHANGE `id` `id` char(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_subscription` SET `id_record` = '' WHERE ISNULL(`id_record`);
ALTER TABLE `ploopi_subscription` CHANGE `id_record` `id_record` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_share` SET `type_share` = '' WHERE ISNULL(`type_share`);
ALTER TABLE `ploopi_share` CHANGE `type_share` `type_share` varchar(16) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_share` SET `id_share` = 0  WHERE ISNULL(`id_share`);
ALTER TABLE `ploopi_share` CHANGE `id_share` `id_share` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_share` SET `id_module_type` = 0  WHERE ISNULL(`id_module_type`);
ALTER TABLE `ploopi_share` CHANGE `id_module_type` `id_module_type` int(10) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `md5id` = '' WHERE ISNULL(`md5id`);
ALTER TABLE `ploopi_documents_file` CHANGE `md5id` `md5id` varchar(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `name` = '' WHERE ISNULL(`name`);
ALTER TABLE `ploopi_documents_file` CHANGE `name` `name` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `label` = '' WHERE ISNULL(`label`);
ALTER TABLE `ploopi_documents_file` CHANGE `label` `label` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `description` = '' WHERE ISNULL(`description`);
ALTER TABLE `ploopi_documents_file` CHANGE `description` `description` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `ref` = '' WHERE ISNULL(`ref`);
ALTER TABLE `ploopi_documents_file` CHANGE `ref` `ref` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `timestp_file` = 0  WHERE ISNULL(`timestp_file`);
ALTER TABLE `ploopi_documents_file` CHANGE `timestp_file` `timestp_file` bigint(14) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `timestp_create` = 0  WHERE ISNULL(`timestp_create`);
ALTER TABLE `ploopi_documents_file` CHANGE `timestp_create` `timestp_create` bigint(14) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `timestp_modify` = 0  WHERE ISNULL(`timestp_modify`);
ALTER TABLE `ploopi_documents_file` CHANGE `timestp_modify` `timestp_modify` bigint(14) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `size` = 0  WHERE ISNULL(`size`);
ALTER TABLE `ploopi_documents_file` CHANGE `size` `size` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `extension` = '' WHERE ISNULL(`extension`);
ALTER TABLE `ploopi_documents_file` CHANGE `extension` `extension` varchar(20) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `parents` = '' WHERE ISNULL(`parents`);
ALTER TABLE `ploopi_documents_file` CHANGE `parents` `parents` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `content` = '' WHERE ISNULL(`content`);
ALTER TABLE `ploopi_documents_file` CHANGE `content` `content` longtext NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `nbclick` = 0  WHERE ISNULL(`nbclick`);
ALTER TABLE `ploopi_documents_file` CHANGE `nbclick` `nbclick` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `id_folder` = 0  WHERE ISNULL(`id_folder`);
ALTER TABLE `ploopi_documents_file` CHANGE `id_folder` `id_folder` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `id_user_modify` = 0  WHERE ISNULL(`id_user_modify`);
ALTER TABLE `ploopi_documents_file` CHANGE `id_user_modify` `id_user_modify` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `id_user` = 0  WHERE ISNULL(`id_user`);
ALTER TABLE `ploopi_documents_file` CHANGE `id_user` `id_user` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `id_workspace` = 0  WHERE ISNULL(`id_workspace`);
ALTER TABLE `ploopi_documents_file` CHANGE `id_workspace` `id_workspace` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `id_module` = 0  WHERE ISNULL(`id_module`);
ALTER TABLE `ploopi_documents_file` CHANGE `id_module` `id_module` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_documents_file` SET `id_record` = '' WHERE ISNULL(`id_record`);
ALTER TABLE `ploopi_documents_file` CHANGE `id_record` `id_record` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_ticket_status` SET `timestp` = 0  WHERE ISNULL(`timestp`);
ALTER TABLE `ploopi_ticket_status` CHANGE `timestp` `timestp` bigint(14) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_workspace_user` SET `adminlevel` = 0  WHERE ISNULL(`adminlevel`);
ALTER TABLE `ploopi_workspace_user` CHANGE `adminlevel` `adminlevel` tinyint(3) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_ticket` SET `title` = '' WHERE ISNULL(`title`);
ALTER TABLE `ploopi_ticket` CHANGE `title` `title` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_ticket` SET `message` = '' WHERE ISNULL(`message`);
ALTER TABLE `ploopi_ticket` CHANGE `message` `message` longtext NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_ticket` SET `id_object` = 0  WHERE ISNULL(`id_object`);
ALTER TABLE `ploopi_ticket` CHANGE `id_object` `id_object` int(10) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_ticket` SET `id_module` = 0  WHERE ISNULL(`id_module`);
ALTER TABLE `ploopi_ticket` CHANGE `id_module` `id_module` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_ticket` SET `id_record` = '' WHERE ISNULL(`id_record`);
ALTER TABLE `ploopi_ticket` CHANGE `id_record` `id_record` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_ticket` SET `id_user` = 0  WHERE ISNULL(`id_user`);
ALTER TABLE `ploopi_ticket` CHANGE `id_user` `id_user` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_group` SET `id_group` = 0  WHERE ISNULL(`id_group`);
ALTER TABLE `ploopi_group` CHANGE `id_group` `id_group` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_group` SET `protected` = 0  WHERE ISNULL(`protected`);
ALTER TABLE `ploopi_group` CHANGE `protected` `protected` tinyint(1) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_group` SET `parents` = '' WHERE ISNULL(`parents`);
ALTER TABLE `ploopi_group` CHANGE `parents` `parents` varchar(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_param_type` SET `default_value` = '' WHERE ISNULL(`default_value`);
ALTER TABLE `ploopi_param_type` CHANGE `default_value` `default_value` text NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_param_type` SET `description` = '' WHERE ISNULL(`description`);
ALTER TABLE `ploopi_param_type` CHANGE `description` `description` longtext NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_param_type` SET `label` = '' WHERE ISNULL(`label`);
ALTER TABLE `ploopi_param_type` CHANGE `label` `label` varchar(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_object` SET `label` = '' WHERE ISNULL(`label`);
ALTER TABLE `ploopi_mb_object` CHANGE `label` `label` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_object` SET `script` = '' WHERE ISNULL(`script`);
ALTER TABLE `ploopi_mb_object` CHANGE `script` `script` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_confirmation_code` SET `action` = '' WHERE ISNULL(`action`);
ALTER TABLE `ploopi_confirmation_code` CHANGE `action` `action` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_confirmation_code` SET `code` = '' WHERE ISNULL(`code`);
ALTER TABLE `ploopi_confirmation_code` CHANGE `code` `code` varchar(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_workspace_group` SET `adminlevel` = 0  WHERE ISNULL(`adminlevel`);
ALTER TABLE `ploopi_workspace_group` CHANGE `adminlevel` `adminlevel` tinyint(3) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_mb_relation` SET `tablesrc` = '' WHERE ISNULL(`tablesrc`);
ALTER TABLE `ploopi_mb_relation` CHANGE `tablesrc` `tablesrc` varchar(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_relation` SET `fieldsrc` = '' WHERE ISNULL(`fieldsrc`);
ALTER TABLE `ploopi_mb_relation` CHANGE `fieldsrc` `fieldsrc` varchar(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_relation` SET `tabledest` = '' WHERE ISNULL(`tabledest`);
ALTER TABLE `ploopi_mb_relation` CHANGE `tabledest` `tabledest` varchar(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_relation` SET `fielddest` = '' WHERE ISNULL(`fielddest`);
ALTER TABLE `ploopi_mb_relation` CHANGE `fielddest` `fielddest` varchar(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_role` SET `id_module` = 0  WHERE ISNULL(`id_module`);
ALTER TABLE `ploopi_role` CHANGE `id_module` `id_module` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_role` SET `id_workspace` = 0  WHERE ISNULL(`id_workspace`);
ALTER TABLE `ploopi_role` CHANGE `id_workspace` `id_workspace` int(10) NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_role` SET `label` = '' WHERE ISNULL(`label`);
ALTER TABLE `ploopi_role` CHANGE `label` `label` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_role` SET `description` = '' WHERE ISNULL(`description`);
ALTER TABLE `ploopi_role` CHANGE `description` `description` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_module_type` SET `label` = '' WHERE ISNULL(`label`);
ALTER TABLE `ploopi_module_type` CHANGE `label` `label` varchar(100) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_module_type` SET `publicparam` = 0  WHERE ISNULL(`publicparam`);
ALTER TABLE `ploopi_module_type` CHANGE `publicparam` `publicparam` tinyint(1) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_module_type` SET `description` = '' WHERE ISNULL(`description`);
ALTER TABLE `ploopi_module_type` CHANGE `description` `description` longtext NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_module_type` SET `version` = '' WHERE ISNULL(`version`);
ALTER TABLE `ploopi_module_type` CHANGE `version` `version` varchar(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_module_type` SET `author` = '' WHERE ISNULL(`author`);
ALTER TABLE `ploopi_module_type` CHANGE `author` `author` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_captcha` SET `id` = '' WHERE ISNULL(`id`);
ALTER TABLE `ploopi_captcha` CHANGE `id` `id` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_captcha` SET `cptuse` = 0  WHERE ISNULL(`cptuse`);
ALTER TABLE `ploopi_captcha` CHANGE `cptuse` `cptuse` int(10) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_captcha` SET `codesound` = '' WHERE ISNULL(`codesound`);
ALTER TABLE `ploopi_captcha` CHANGE `codesound` `codesound` varchar(20) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_captcha` SET `code` = '' WHERE ISNULL(`code`);
ALTER TABLE `ploopi_captcha` CHANGE `code` `code` varchar(20) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_captcha` SET `time` = 0  WHERE ISNULL(`time`);
ALTER TABLE `ploopi_captcha` CHANGE `time` `time` int(20) unsigned NOT NULL DEFAULT 0  COMMENT '' ;
UPDATE `ploopi_index_element` SET `id_record` = '' WHERE ISNULL(`id_record`);
ALTER TABLE `ploopi_index_element` CHANGE `id_record` `id_record` char(64) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_index_element` SET `label` = '' WHERE ISNULL(`label`);
ALTER TABLE `ploopi_index_element` CHANGE `label` `label` char(128) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mimetype` SET `ext` = '' WHERE ISNULL(`ext`);
ALTER TABLE `ploopi_mimetype` CHANGE `ext` `ext` varchar(10) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mimetype` SET `mimetype` = '' WHERE ISNULL(`mimetype`);
ALTER TABLE `ploopi_mimetype` CHANGE `mimetype` `mimetype` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mimetype` SET `filetype` = '' WHERE ISNULL(`filetype`);
ALTER TABLE `ploopi_mimetype` CHANGE `filetype` `filetype` varchar(50) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mimetype` SET `group` = '' WHERE ISNULL(`group`);
ALTER TABLE `ploopi_mimetype` CHANGE `group` `group` varchar(30) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_serializedvar` SET `id` = '' WHERE ISNULL(`id`);
ALTER TABLE `ploopi_serializedvar` CHANGE `id` `id` char(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_serializedvar` SET `id_session` = '' WHERE ISNULL(`id_session`);
ALTER TABLE `ploopi_serializedvar` CHANGE `id_session` `id_session` char(32) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_serializedvar` SET `data` = '' WHERE ISNULL(`data`);
ALTER TABLE `ploopi_serializedvar` CHANGE `data` `data` longblob NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_action` SET `label` = '' WHERE ISNULL(`label`);
ALTER TABLE `ploopi_mb_action` CHANGE `label` `label` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_action` SET `description` = '' WHERE ISNULL(`description`);
ALTER TABLE `ploopi_mb_action` CHANGE `description` `description` varchar(255) NOT NULL DEFAULT ''  COMMENT '' ;
UPDATE `ploopi_mb_action` SET `id_workspace` = 0  WHERE ISNULL(`id_workspace`);
ALTER TABLE `ploopi_mb_action` CHANGE `id_workspace` `id_workspace` int(10) NOT NULL DEFAULT 0  COMMENT '' ;

UPDATE `ploopi_module_type` SET `version` = '1.9.7.4', `author` = 'Ovensia', `date` = '20200311000000', `description` = 'Noyau du système' WHERE `ploopi_module_type`.`id` = 1;
