ALTER TABLE `ploopi_annotation` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_annotation_tag` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_captcha` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_confirmation_code` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_connecteduser` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_documents_ext` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_documents_file` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_documents_folder` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_group` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_group_user` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_index_element` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_index_keyword_element` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_index_phonetic_element` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_index_stem_element` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_log` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mb_action` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mb_field` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mb_object` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mb_relation` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mb_schema` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mb_table` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mb_wce_object` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mimetype` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_booking_event` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_booking_event_detail` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_booking_event_subresource` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_booking_resource` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_booking_resource_workspace` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_booking_resourcetype` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_booking_subresource` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_dbreport_query` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_dbreport_query_module_type` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_dbreport_queryfield` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_dbreport_queryrelation` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_dbreport_querytable` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_directory_contact` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_directory_favorites` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_directory_heading` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_directory_list` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_directory_speeddialing` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_doc_file` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_doc_file_draft` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_doc_file_history` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_doc_folder` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_doc_keyword` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_doc_keyword_file` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_doc_meta` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_doc_parser` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_forms_field` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_forms_form` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_forms_graphic` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_forms_group` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_webedit_article` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_webedit_article_backup` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_webedit_article_comment` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_webedit_article_draft` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_webedit_article_object` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_webedit_article_tag` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_webedit_counter` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_webedit_docfile` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_webedit_heading` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_webedit_heading_subscriber` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_webedit_tag` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_wiki_page` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_mod_wiki_page_history` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_module` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_module_type` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_module_workspace` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_param_choice` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_param_default` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_param_type` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_param_user` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_param_workspace` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_role` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_role_action` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_serializedvar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_session` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_share` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_subscription` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_subscription_action` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_tag` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_ticket` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_ticket_dest` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_ticket_status` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_ticket_watch` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_user` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_user_action_log` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_validation` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_workspace` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_workspace_group` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_workspace_group_role` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_workspace_user` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `ploopi_workspace_user_role` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE `ploopi_annotation` CHANGE `title` `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_annotation` CHANGE `content` `content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_annotation` CHANGE `object_label` `object_label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_annotation` CHANGE `type_annotation` `type_annotation` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_annotation` CHANGE `date_annotation` `date_annotation` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_annotation` CHANGE `id_record` `id_record` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  ;
ALTER TABLE `ploopi_annotation` CHANGE `id_element` `id_element` char(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0'  ;
ALTER TABLE `ploopi_captcha` CHANGE `id` `id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_captcha` CHANGE `codesound` `codesound` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_captcha` CHANGE `code` `code` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_confirmation_code` CHANGE `action` `action` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_confirmation_code` CHANGE `code` `code` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_connecteduser` CHANGE `sid` `sid` char(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0'  ;
ALTER TABLE `ploopi_connecteduser` CHANGE `ip` `ip` char(15) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_connecteduser` CHANGE `domain` `domain` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_documents_ext` CHANGE `ext` `ext` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_documents_ext` CHANGE `filetype` `filetype` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci  ;
ALTER TABLE `ploopi_documents_file` CHANGE `md5id` `md5id` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_documents_file` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  ;
ALTER TABLE `ploopi_documents_file` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_documents_file` CHANGE `description` `description` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_documents_file` CHANGE `ref` `ref` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_documents_file` CHANGE `extension` `extension` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci  ;
ALTER TABLE `ploopi_documents_file` CHANGE `parents` `parents` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_documents_file` CHANGE `content` `content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_documents_file` CHANGE `id_record` `id_record` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_documents_folder` CHANGE `md5id` `md5id` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_documents_folder` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_documents_folder` CHANGE `description` `description` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_documents_folder` CHANGE `parents` `parents` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0'  ;
ALTER TABLE `ploopi_documents_folder` CHANGE `id_record` `id_record` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_group` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_group` CHANGE `parents` `parents` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci  ;
ALTER TABLE `ploopi_index_element` CHANGE `id_record` `id_record` char(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_index_element` CHANGE `label` `label` char(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_index_keyword_element` CHANGE `keyword` `keyword` char(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_index_phonetic_element` CHANGE `phonetic` `phonetic` char(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_index_stem_element` CHANGE `stem` `stem` char(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_log` CHANGE `request_method` `request_method` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_log` CHANGE `query_string` `query_string` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_log` CHANGE `remote_addr` `remote_addr` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_log` CHANGE `script_filename` `script_filename` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_log` CHANGE `path_translated` `path_translated` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_log` CHANGE `script_name` `script_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_log` CHANGE `request_uri` `request_uri` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_log` CHANGE `browser` `browser` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_log` CHANGE `system` `system` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mb_action` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mb_action` CHANGE `description` `description` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mb_field` CHANGE `tablename` `tablename` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mb_field` CHANGE `name` `name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mb_field` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mb_field` CHANGE `type` `type` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mb_object` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mb_object` CHANGE `script` `script` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mb_relation` CHANGE `tablesrc` `tablesrc` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci  ;
ALTER TABLE `ploopi_mb_relation` CHANGE `fieldsrc` `fieldsrc` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci  ;
ALTER TABLE `ploopi_mb_relation` CHANGE `tabledest` `tabledest` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci  ;
ALTER TABLE `ploopi_mb_relation` CHANGE `fielddest` `fielddest` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci  ;
ALTER TABLE `ploopi_mb_schema` CHANGE `tablesrc` `tablesrc` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mb_schema` CHANGE `tabledest` `tabledest` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mb_table` CHANGE `name` `name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mb_table` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mb_wce_object` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mb_wce_object` CHANGE `script` `script` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mb_wce_object` CHANGE `select_id` `select_id` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mb_wce_object` CHANGE `select_label` `select_label` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mb_wce_object` CHANGE `select_table` `select_table` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mimetype` CHANGE `ext` `ext` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mimetype` CHANGE `mimetype` `mimetype` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mimetype` CHANGE `filetype` `filetype` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mimetype` CHANGE `group` `group` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_booking_event` CHANGE `object` `object` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_booking_event` CHANGE `periodicity` `periodicity` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_booking_event` CHANGE `comment` `comment` mediumtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_booking_event_detail` CHANGE `cancelreason` `cancelreason` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_booking_event_detail` CHANGE `message` `message` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_booking_event_detail` CHANGE `emails` `emails` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_booking_resource` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_booking_resource` CHANGE `reference` `reference` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_booking_resource` CHANGE `color` `color` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_booking_resourcetype` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_booking_subresource` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_booking_subresource` CHANGE `reference` `reference` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `ws_id` `ws_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `ws_code` `ws_code` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `ws_ip` `ws_ip` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `transformation` `transformation` enum('','pivot_table') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart` `chart` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'line'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_title` `chart_title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_subtitle` `chart_subtitle` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_background` `chart_background` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '#FFFFFF'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_colorset` `chart_colorset` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'default'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_color` `chart_color` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '#FF0000'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_font` `chart_font` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_border_color` `chart_border_color` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '#A0A0A0'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_title_font_color` `chart_title_font_color` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '#000000'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_axis_font_color` `chart_axis_font_color` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '#888888'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_axis_color` `chart_axis_color` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '#C0C0C0'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_legend_font_color` `chart_legend_font_color` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '#888888'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_legend_align` `chart_legend_align` enum('left','center','right') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'center'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_legend_valign` `chart_legend_valign` enum('top','center','bottom') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'bottom'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_indexes_font_color` `chart_indexes_font_color` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '#888888'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_indexes_format` `chart_indexes_format` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '{y}'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_interlaced_x_color` `chart_interlaced_x_color` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ' #FFFFFF'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_interlaced_y_color` `chart_interlaced_y_color` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '#F0F0F0'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_grid_color` `chart_grid_color` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '#D0D0D0'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_value_x_prefix` `chart_value_x_prefix` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_value_x_suffix` `chart_value_x_suffix` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_value_x_format` `chart_value_x_format` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_value_y_prefix` `chart_value_y_prefix` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_value_y_suffix` `chart_value_y_suffix` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_value_y_format` `chart_value_y_format` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_sort_x` `chart_sort_x` enum('asc','desc','asc_val','desc_val') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'asc'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_sort_y` `chart_sort_y` enum('asc','desc','asc_val','desc_val') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'asc'  ;
ALTER TABLE `ploopi_mod_dbreport_query` CHANGE `chart_tooltip_format` `chart_tooltip_format` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '<span style="color:{series.color}">{series.name}</span>: <b>{point.y:.0f}</b> ({point.percentage:.0f}%)<br/>'  ;
ALTER TABLE `ploopi_mod_dbreport_queryfield` CHANGE `tablename` `tablename` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryfield` CHANGE `fieldname` `fieldname` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryfield` CHANGE `label` `label` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryfield` CHANGE `function` `function` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryfield` CHANGE `function_group` `function_group` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryfield` CHANGE `sort` `sort` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryfield` CHANGE `criteria` `criteria` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryfield` CHANGE `type_criteria` `type_criteria` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryfield` CHANGE `or` `or` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryfield` CHANGE `type_or` `type_or` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryfield` CHANGE `intervals` `intervals` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryfield` CHANGE `operation` `operation` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryrelation` CHANGE `tablename_src` `tablename_src` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryrelation` CHANGE `fieldname_src` `fieldname_src` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryrelation` CHANGE `tablename_dest` `tablename_dest` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_queryrelation` CHANGE `fieldname_dest` `fieldname_dest` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_querytable` CHANGE `tablename` `tablename` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_dbreport_querytable` CHANGE `alias` `alias` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` DROP INDEX FT;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `lastname` `lastname` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `firstname` `firstname` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `service` `service` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `function` `function` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `phone` `phone` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `mobile` `mobile` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `fax` `fax` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `email` `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `address` `address` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `postalcode` `postalcode` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `city` `city` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `country` `country` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `comments` `comments` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `number` `number` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `building` `building` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `floor` `floor` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `office` `office` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `civility` `civility` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` CHANGE `rank` `rank` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_contact` ADD FULLTEXT( `lastname`, `firstname`, `service`, `function`, `city`, `country`, `comments`, `number`, `office`);
ALTER TABLE `ploopi_mod_directory_heading` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_heading` CHANGE `description` `description` mediumtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_heading` CHANGE `phone` `phone` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_heading` CHANGE `fax` `fax` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_heading` CHANGE `address` `address` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_heading` CHANGE `postalcode` `postalcode` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_heading` CHANGE `city` `city` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_heading` CHANGE `country` `country` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_list` CHANGE `label` `label` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_speeddialing` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_speeddialing` CHANGE `number` `number` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_speeddialing` CHANGE `shortnumber` `shortnumber` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_directory_speeddialing` CHANGE `heading` `heading` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_doc_file` CHANGE `md5id` `md5id` char(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_doc_file` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  ;
ALTER TABLE `ploopi_mod_doc_file` CHANGE `description` `description` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_doc_file` CHANGE `extension` `extension` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci  ;
ALTER TABLE `ploopi_mod_doc_file` CHANGE `parents` `parents` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_doc_file` CHANGE `content` `content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_doc_file` CHANGE `metadata` `metadata` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `md5id` `md5id` char(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `description` `description` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `extension` `extension` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_doc_file_draft` CHANGE `parents` `parents` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_doc_file_history` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_doc_file_history` CHANGE `description` `description` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_doc_file_history` CHANGE `extension` `extension` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `description` `description` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `foldertype` `foldertype` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'private'  ;
ALTER TABLE `ploopi_mod_doc_folder` CHANGE `parents` `parents` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0'  ;
ALTER TABLE `ploopi_mod_doc_keyword` CHANGE `keyword` `keyword` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_doc_keyword` CHANGE `twoletters` `twoletters` char(2) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_doc_meta` CHANGE `meta` `meta` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_doc_meta` CHANGE `value` `value` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_doc_parser` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mod_doc_parser` CHANGE `path` `path` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mod_doc_parser` CHANGE `extension` `extension` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_field` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_forms_field` CHANGE `fieldname` `fieldname` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mod_forms_field` CHANGE `type` `type` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_forms_field` CHANGE `format` `format` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_forms_field` CHANGE `values` `values` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_forms_field` CHANGE `formula` `formula` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_field` CHANGE `description` `description` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_forms_field` CHANGE `xhtmlcontent` `xhtmlcontent` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_field` CHANGE `xhtmlcontent_cleaned` `xhtmlcontent_cleaned` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_field` CHANGE `style_field` `style_field` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_field` CHANGE `style_form` `style_form` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_field` CHANGE `defaultvalue` `defaultvalue` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_forms_form` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_forms_form` CHANGE `description` `description` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_forms_form` CHANGE `email_from` `email_from` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_form` CHANGE `email` `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_forms_form` CHANGE `style` `style` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_form` CHANGE `model` `model` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_forms_form` CHANGE `typeform` `typeform` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'app'  ;
ALTER TABLE `ploopi_mod_forms_form` CHANGE `option_modify` `option_modify` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'nobody'  ;
ALTER TABLE `ploopi_mod_forms_form` CHANGE `option_view` `option_view` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'global'  ;
ALTER TABLE `ploopi_mod_forms_form` CHANGE `cms_response` `cms_response` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `description` `description` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `type` `type` enum('pie','pie3d','bar','barc','line','linec','radar','radarc') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line_aggregation` `line_aggregation` enum('hour','day','week','month') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `operation` `operation` enum('count','sum','avg') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line1_operation` `line1_operation` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line2_operation` `line2_operation` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line3_operation` `line3_operation` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line4_operation` `line4_operation` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line5_operation` `line5_operation` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line1_color` `line1_color` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line2_color` `line2_color` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line3_color` `line3_color` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line4_color` `line4_color` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line5_color` `line5_color` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line1_filter_op` `line1_filter_op` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line2_filter_op` `line2_filter_op` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line3_filter_op` `line3_filter_op` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line4_filter_op` `line4_filter_op` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line5_filter_op` `line5_filter_op` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line1_filter_value` `line1_filter_value` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line2_filter_value` `line2_filter_value` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line3_filter_value` `line3_filter_value` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line4_filter_value` `line4_filter_value` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line5_filter_value` `line5_filter_value` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line1_legend` `line1_legend` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line2_legend` `line2_legend` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line3_legend` `line3_legend` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line4_legend` `line4_legend` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `line5_legend` `line5_legend` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `pie_color1` `pie_color1` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_graphic` CHANGE `pie_color2` `pie_color2` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_group` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_group` CHANGE `description` `description` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_group` CHANGE `conditions` `conditions` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_forms_group` CHANGE `formula` `formula` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article` CHANGE `reference` `reference` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mod_webedit_article` CHANGE `title` `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article` CHANGE `metakeywords` `metakeywords` mediumtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article` CHANGE `content` `content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article` CHANGE `content_cleaned` `content_cleaned` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article` CHANGE `metadescription` `metadescription` mediumtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article` CHANGE `metatitle` `metatitle` mediumtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article` CHANGE `author` `author` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article` CHANGE `version` `version` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mod_webedit_article` CHANGE `status` `status` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mod_webedit_article` CHANGE `tags` `tags` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article` CHANGE `headcontent` `headcontent` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_backup` CHANGE `content` `content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_comment` CHANGE `comment` `comment` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_comment` CHANGE `email` `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_comment` CHANGE `nickname` `nickname` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_draft` CHANGE `reference` `reference` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mod_webedit_article_draft` CHANGE `title` `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_draft` CHANGE `metakeywords` `metakeywords` mediumtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_draft` CHANGE `content` `content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_draft` CHANGE `content_cleaned` `content_cleaned` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_draft` CHANGE `metadescription` `metadescription` mediumtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_draft` CHANGE `metatitle` `metatitle` mediumtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_draft` CHANGE `author` `author` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_draft` CHANGE `version` `version` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mod_webedit_article_draft` CHANGE `status` `status` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mod_webedit_article_draft` CHANGE `tags` `tags` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_draft` CHANGE `headcontent` `headcontent` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_article_object` CHANGE `id_record` `id_record` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_docfile` CHANGE `md5id_docfile` `md5id_docfile` char(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_heading` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_webedit_heading` CHANGE `description` `description` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_mod_webedit_heading` CHANGE `template` `template` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mod_webedit_heading` CHANGE `parents` `parents` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_mod_webedit_heading` CHANGE `content_type` `content_type` char(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'article_first'  ;
ALTER TABLE `ploopi_mod_webedit_heading` CHANGE `color` `color` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_heading` CHANGE `linkedpage` `linkedpage` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0'  ;
ALTER TABLE `ploopi_mod_webedit_heading` CHANGE `url` `url` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_heading` CHANGE `sortmode` `sortmode` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_heading` CHANGE `free1` `free1` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_heading` CHANGE `free2` `free2` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_heading` CHANGE `iprules` `iprules` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_heading_subscriber` CHANGE `email` `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_webedit_tag` CHANGE `tag` `tag` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_wiki_page` CHANGE `id` `id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_wiki_page` CHANGE `content` `content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_wiki_page` CHANGE `tags` `tags` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_wiki_page_history` CHANGE `id_page` `id_page` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_mod_wiki_page_history` CHANGE `content` `content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_module_type` CHANGE `label` `label` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci  ;
ALTER TABLE `ploopi_module_type` CHANGE `description` `description` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_module_type` CHANGE `version` `version` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_module_type` CHANGE `author` `author` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_module_type` CHANGE `date` `date` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_module_workspace` CHANGE `blockposition` `blockposition` char(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'left'  ;
ALTER TABLE `ploopi_param_choice` CHANGE `name` `name` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_param_choice` CHANGE `value` `value` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_param_choice` CHANGE `displayed_value` `displayed_value` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_param_default` CHANGE `name` `name` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_param_default` CHANGE `value` `value` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_param_type` CHANGE `name` `name` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_param_type` CHANGE `default_value` `default_value` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_param_type` CHANGE `description` `description` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_param_type` CHANGE `label` `label` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_param_user` CHANGE `name` `name` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_param_user` CHANGE `value` `value` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_param_workspace` CHANGE `name` `name` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_param_workspace` CHANGE `value` `value` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_role` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_role` CHANGE `description` `description` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_serializedvar` CHANGE `id` `id` char(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_serializedvar` CHANGE `id_session` `id_session` char(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_serializedvar` CHANGE `data` `data` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_session` CHANGE `id` `id` char(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_session` CHANGE `data` `data` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_share` CHANGE `type_share` `type_share` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0'  ;
ALTER TABLE `ploopi_subscription` CHANGE `id` `id` char(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_subscription` CHANGE `id_record` `id_record` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_subscription_action` CHANGE `id_subscription` `id_subscription` char(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_tag` CHANGE `tag` `tag` char(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_tag` CHANGE `tag_clean` `tag_clean` char(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_ticket` CHANGE `title` `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_ticket` CHANGE `message` `message` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_ticket` CHANGE `object_label` `object_label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_ticket` CHANGE `id_record` `id_record` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_user` DROP INDEX ft;
ALTER TABLE `ploopi_user` CHANGE `lastname` `lastname` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `firstname` `firstname` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `login` `login` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `password` `password` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `email` `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `phone` `phone` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `fax` `fax` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `comments` `comments` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `address` `address` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `mobile` `mobile` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `entity` `entity` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `service` `service` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `service2` `service2` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `function` `function` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `number` `number` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `postalcode` `postalcode` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `city` `city` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `country` `country` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `color` `color` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_user` CHANGE `timezone` `timezone` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `building` `building` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `floor` `floor` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `office` `office` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `civility` `civility` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` CHANGE `rank` `rank` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user` ADD FULLTEXT( `lastname`, `firstname`, `email`, `comments`, `service`, `service2`, `function`, `city`, `building`, `floor`, `office`, `rank`);
ALTER TABLE `ploopi_user_action_log` CHANGE `id_record` `id_record` char(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user_action_log` CHANGE `ip` `ip` char(16) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user_action_log` CHANGE `user` `user` char(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user_action_log` CHANGE `workspace` `workspace` char(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user_action_log` CHANGE `action` `action` char(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user_action_log` CHANGE `module_type` `module_type` char(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_user_action_log` CHANGE `module` `module` char(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_validation` CHANGE `id_record` `id_record` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_validation` CHANGE `type_validation` `type_validation` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '0'  ;
ALTER TABLE `ploopi_workspace` CHANGE `label` `label` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'NULL'  ;
ALTER TABLE `ploopi_workspace` CHANGE `code` `code` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_workspace` CHANGE `parents` `parents` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'NULL'  ;
ALTER TABLE `ploopi_workspace` CHANGE `iprules` `iprules` text CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_workspace` CHANGE `macrules` `macrules` text CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_workspace` CHANGE `template` `template` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_workspace` CHANGE `backoffice_domainlist` `backoffice_domainlist` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_workspace` CHANGE `title` `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_workspace` CHANGE `meta_description` `meta_description` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_workspace` CHANGE `meta_keywords` `meta_keywords` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;
ALTER TABLE `ploopi_workspace` CHANGE `meta_author` `meta_author` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_workspace` CHANGE `meta_copyright` `meta_copyright` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''  ;
ALTER TABLE `ploopi_workspace` CHANGE `meta_robots` `meta_robots` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'index, follow, all'  ;
ALTER TABLE `ploopi_workspace` CHANGE `frontoffice_domainlist` `frontoffice_domainlist` longtext CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL  ;
ALTER TABLE `ploopi_workspace` CHANGE `mail_model` `mail_model` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  ;


ALTER TABLE `ploopi_user` CHANGE `password` `password` VARCHAR( 128 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `ploopi_session` CHANGE `data` `data` LONGBLOB NULL DEFAULT NULL;
ALTER TABLE `ploopi_serializedvar` CHANGE `data` `data` LONGBLOB NULL DEFAULT NULL;

ALTER TABLE  `ploopi_user` ADD  `last_connection` BIGINT( 14 ) UNSIGNED NOT NULL DEFAULT  '0', ADD INDEX (  `last_connection` );

UPDATE `ploopi_module_type` SET `version` = '1.9.7.1', `author` = 'Ovensia', `date` = '20190430000000', `description` = 'Noyau du système' WHERE `ploopi_module_type`.`id` = 1;
